---
title: "Spectra"
author: "Janica Bühler"
date: "4 Juni 2021"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(PaleoSpec)
library(nest)
library(tidyverse)
```

First, read in data: annual and downsampled

```{r}
ENTITY_INFO <- read.csv("DATA/SISAL1k_entity_info.csv")
FULL <- list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list())
DOWN <- list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list())
for(Model in c("HadCM3", "ECHAM5", "GISS", "CESM", "isoGSM")){
  FULL[[Model]] = read.csv(paste0("DATA/SISAL1k_annual_",Model,".csv"))
  DOWN[[Model]] = read.csv(paste0("DATA/SISAL1k_ds_", Model,".csv"))
}
```

Now calculate the spectra:
```{r warning=FALSE}
source("Functions/event_synchronization.R")
source("Functions/SubsampleTimeseriesBlock_highresNA.R")
source('Functions/Filter/EASY_Sensor_WM4.R')
source('Functions/Filter/filter_function3.R')
source('Functions/filter_window.R')

filter_time = 2.5


SPECTRA <- list(FULL = list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list()),
                FULL_D = list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list()),
                DOWN = list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list()),
                DOWN_FILTER = list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list()),
                DOWN_D = list(HadCM3 = list(), ECHAM5 = list(), GISS = list(), CESM = list(), isoGSM = list()),
                RECD = list(d18O = list(), d13C = list()),
                RECD_D = list(d18O = list(), d13C = list()))
for(Model in c("HadCM3", "ECHAM5", "GISS", "CESM", "isoGSM")){
  print(Model)
  for(var in c("ISOT", "ITIF")){
    SPECTRA$FULL[[Model]][[var]] <- list()
    SPECTRA$FULL_D[[Model]][[var]] <- list()
    SPECTRA$DOWN[[Model]][[var]] <- list()
    SPECTRA$DOWN_FILTER[[Model]][[var]] <- list()
    SPECTRA$DOWN_D[[Model]][[var]] <- list()
    
    for(entity in ENTITY_INFO$entity_id){
      data_down = DOWN[[Model]] %>% filter(entity_id == entity)
      data_full = FULL[[Model]] %>% filter(entity_id == entity)
      if(sum(is.na(data_down$d13C_measurement))>length(data_down$d13C_measurement)/4*3){next}
      if(all(is.na(data_full[[var]]))){next}
      if(Model %in% c("CESM", "isoGSM") & entity == 378){next}
      if(Model %in% c("ECHAM5") & entity %in% c(672, 598)){next}
      if(Model == "CESM" & entity == 546){next}
      
      data_down[[paste0(var,"_d")]]  = irr_detrend(TS = list(time = data_down$year_BP, value = data_down[[var]]))$value
      data_full[[paste0(var,"_d")]]  = irr_detrend(TS = list(time = data_full$year_BP, value = data_full[[var]]))$value
      
      #Full spectra
      name = paste0("ENTITY", entity)
      SPECTRA$FULL[[Model]][[var]][[name]] = SpecMTM(ts(data = na.omit(rev(data_full[[var]])), start = LastElement(data_full$year_BP), end = FirstElement(data_full$year_BP), deltat = 1), plot = F)
      SPECTRA$FULL_D[[Model]][[var]][[name]] = SpecMTM(ts(data = na.omit(rev(data_full[[paste0(var,"_d")]])), start = LastElement(data_full$year_BP), end = FirstElement(data_full$year_BP), deltat = 1), plot = F)
      
      #Down spectra
      if(sum(is.na(data_down[[var]]))>length(data_down[[var]])/4*3){next}
      start_ts = FirstElement(data_down$year_BP)
      length = length(data_down$year_BP)
      stop_ts = LastElement(data_down$year_BP)
      if(length > (stop_ts-start_ts)){length = (stop_ts-start_ts)}
      stop_ts = floor((stop_ts-start_ts)/length)*length+start_ts
      record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down[[var]],time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
      #record = na.omit(record)
      #data = ts(data = as.numeric(record), start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
      SPECTRA$DOWN[[Model]][[var]][[name]] = SpecMTM(na.omit(record), plot = F)
      
      record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down[[paste0(var,"_d")]],time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
      #record = na.omit(record)
      #data = ts(data = as.numeric(record), start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
      SPECTRA$DOWN_D[[Model]][[var]][[name]] = SpecMTM(na.omit(record), plot = F)
      
      
      #FILTER:
      diff = floor((LastElement(data_down$year_BP)-FirstElement(data_down$year_BP))/length(data_down$year_BP))
      if(diff<1){diff = 1}
      #1) filter on full
      Results <- easy_sensor_wm4(1.0, na.omit(data_full[[var]]), filter_time)
      time_new = seq(FirstElement(data_full$year_BP), LastElement(data_full$year_BP)-(length(Results)-length(data_full[[var]])), by = -1)
      data  = filter_window(ts(data = rev(Results), start = LastElement(time_new), end = FirstElement(time_new), deltat = 1))
      #2) full downsample
      if(length(data_down$year_BP)>1000){
        data_ds <- SubsampleTimeseriesBlock_highresNA(data, data_down$year_BP)
        value = na.omit(as.numeric(data_ds))
        time = data_down$year_BP[!is.na(as.numeric(data_ds))]
        #3) equidistancing
        data_ds_eq <- PaleoSpec::MakeEquidistant(time, value,
                                                 time.target = seq(from = FirstElement(time), to = LastElement(time), by = diff))
      }else{
        data_ds <- SubsampleTimeseriesBlock_highresNA(data, data_down$year_BP)
        #3) equidistancing
        #data_ds_eq <- PaleoSpec::MakeEquidistant(data_down$year_BP[!is.na(as.numeric(data_ds))], na.omit(as.numeric(data_ds)),
        #                                         time.target = seq(from = FirstElement(data_down$year_BP), to = LastElement(data_down$year_BP), by = diff))
        data_ds_eq = PaleoSpec::MakeEquidistant(data_down$year_BP[!is.na(as.numeric(data_ds))], na.omit(as.numeric(data_ds)),
                                                  time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
      }
      
      #4) spectrum
      if(length(na.omit(data_ds_eq))>8){SPECTRA$DOWN_FILTER[[Model]][[var]][[name]] = SpecMTM(na.omit(data_ds_eq), plot = F)}
      
    }
    if(Model == "GISS"){
      for(var_1 in c("ISOT", "ITIF")){
        SPECTRA$FULL$GISS[[var_1]]$ENTITY33 <- NULL
        SPECTRA$DOWN$GISS[[var_1]]$ENTITY33 <- NULL
        SPECTRA$DOWN_FILTER$GISS[[var_1]]$ENTITY33 <- NULL
        SPECTRA$FULL_D$GISS[[var_1]]$ENTITY33 <- NULL
        SPECTRA$DOWN_D$GISS[[var_1]]$ENTITY33 <- NULL

      }
      rm(var_1)
    }
    
    print("Mean Spectra")
    if(length(SPECTRA$FULL[[Model]][[var]]) == 0){next}
    SPECTRA$FULL[[Model]][[var]][["Mean"]] <- MeanSpectrum(SPECTRA$FULL[[Model]][[var]])
    SPECTRA$FULL_D[[Model]][[var]][["Mean"]] <- MeanSpectrum(SPECTRA$FULL_D[[Model]][[var]])
    if(length(SPECTRA$DOWN[[Model]][[var]]) == 0){next}
    SPECTRA$DOWN[[Model]][[var]][["Mean"]] <- MeanSpectrum(SPECTRA$DOWN[[Model]][[var]])
    SPECTRA$DOWN_FILTER[[Model]][[var]][["Mean"]] <- MeanSpectrum(SPECTRA$DOWN_FILTER[[Model]][[var]])
    SPECTRA$DOWN_D[[Model]][[var]][["Mean"]] <- MeanSpectrum(SPECTRA$DOWN_D[[Model]][[var]])
  }
}

print("RECORD")

for(entity in ENTITY_INFO$entity_id){
  #if(entity %in% c(620,621, 623, 447)){next}
  data_down = DOWN$HadCM3 %>% filter(entity_id == entity)
  if(sum(is.na(data_down$d13C_measurement))>length(data_down$d13C_measurement)/4*3){next}
  data_down$d18O_measurement_d  = irr_detrend(TS = list(time = data_down$year_BP, value = data_down$d18O_measurement))$value
  data_down$d13C_measurement_d  = irr_detrend(TS = list(time = data_down$year_BP, value = data_down$d13C_measurement))$value
  
  name = paste0("ENTITY", entity)
  start_ts = ceiling(head(data_down$year_BP, n = 1))
  length = length(data_down$year_BP)
  stop_ts = floor(tail(data_down$year_BP, n = 1))
  if(length > (stop_ts-start_ts)){length = (stop_ts-start_ts)}
  stop_ts = floor((stop_ts-start_ts)/length)*length+start_ts
  record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down$d18O_measurement,time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
  record = na.omit(record)
  data = ts(data = record, start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
  
  SPECTRA$RECD$d18O[[name]] = SpecMTM(data, plot = F)
  
  record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down$d18O_measurement_d,time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
  record = na.omit(record)
  data = ts(data = record, start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
  SPECTRA$RECD_D$d18O[[name]] = SpecMTM(data, plot = F)
  
  if(all(is.na(data_down$d13C_measurement))){next}
  record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down$d13C_measurement,time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
  record = na.omit(record)
  data = ts(data = record, start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
  #plot(data, type = "l")
  SPECTRA$RECD$d13C[[name]] = SpecMTM(data, plot = F)
  
  record = PaleoSpec::MakeEquidistant(data_down$year_BP,data_down$d13C_measurement_d,time.target = seq(from = start_ts, to = stop_ts, by = floor((stop_ts-start_ts)/length)))
  record = na.omit(record)
  data = ts(data = record, start = start_ts, end = stop_ts, deltat = floor((stop_ts-start_ts)/length))
  #lines(data, col = "red")
  #mtext(text = entity, side = 3, line = -2)
  SPECTRA$RECD_D$d13C[[name]] = SpecMTM(data, plot = F)
}

SPECTRA$RECD$d18O[["Mean"]] <- MeanSpectrum(SPECTRA$RECD$d18O)
SPECTRA$RECD$d13C[["Mean"]] <- MeanSpectrum(SPECTRA$RECD$d13C)
SPECTRA$RECD_D$d18O[["Mean"]] <- MeanSpectrum(SPECTRA$RECD_D$d18O)
SPECTRA$RECD_D$d13C[["Mean"]] <- MeanSpectrum(SPECTRA$RECD_D$d13C)



```
Calculate variance of d13C and d18O
```{r}
VARIANCE <- list(d18O = list(), d13C = list(), entity_id = c())

for(entity in ENTITY_INFO$entity_id){
  data_rec = DOWN$HadCM3 %>% filter(entity_id == entity)
  if(sum(is.na(data_rec$d13C_measurement))>length(data_rec$d13C_measurement)/4*3){next}
  VARIANCE$d18O = c(VARIANCE$d18O, var(irr_detrend(TS = list(time = data_rec$year_BP, value = data_rec$d18O_measurement))$value, na.rm = T))
  VARIANCE$d13C = c(VARIANCE$d13C, var(irr_detrend(TS = list(time = data_rec$year_BP, value = data_rec$d13C_measurement))$value, na.rm = T))
  VARIANCE$entity_id = c(VARIANCE$entity_id, entity)
}

VARIANCE$d18O = as.numeric(VARIANCE$d18O)
VARIANCE$d13C = as.numeric(VARIANCE$d13C)
VARIANCE$entity_id = as.numeric(VARIANCE$entity_id)
```



Now comes the plotting. Let's see what we are left with...

```{r}
library(latex2exp)
cex_text = 1.2
cex_text_legend = 1.9
cex_axis = 1
cex_axis_text = 1
lw_smooth =3

cairo_pdf(file = paste0("Plots/Fig_9_Spectra.pdf"), width = 10/2*3, height = 6)

COLZ = c(rgb(112,160,205, max = 255), rgb(0,52,102, max = 255), rgb(178,178,178, max = 255),rgb(0,121,0, max = 255), rgb(196,121,0, max = 255))

COLZ_carbon = "black"
COLZ_grid = adjustcolor("grey", alpha.f = 0.5)

#########################################################################################################
par(mar=c(1,2,0,1),oma=c(3,3,3,3),xaxs="i",yaxs="i",cex=1,lwd=2, mfrow = c(1,3))

# a) first plot is spec ratio btw d18O and d13C speleo
spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$RECD$d13C$Mean$spec$spec
spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$RECD$d13C$Mean$spec$lim.2
spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$RECD$d13C$Mean$spec$lim.1
LPlot(spec_ratio, col = "white",
        ylim = c(0.0002,100), xlim = c(1/300, 0.5),
        ylab = "",
        xaxt = 'n',
        yaxt = "n",
        xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
mtext(expression("PSD ratio"), side = 2, line= 2, at = 1, las = 0, cex = cex_axis_text)

axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)
axis(side=2, at = c(1e-3, 1e-1, 1e1, 1e3), labels = FALSE)
mtext(side=2,at=c(1e-3, 1e-1, 1e1, 1e3),line = 1, c(1e-3, 0.1, 10, 1000),las=1,col="black", cex = cex_axis)

LLines(spec_ratio, col = adjustcolor("black", alpha.f = 0.3), lty = 1, lw = 2)
LLines(LogSmooth(spec_ratio), col = "black", lw = lw_smooth)

mtext(TeX("a) $\\delta^{18}$O$_{speleo}$/$\\delta^{13}$C$_{speleo}"), side = 3, line = -3, adj = 0.05, cex = cex_text)

#b) second plot is spec ratio between speleo-d18O and annual d18O
LPlot(spec_ratio, col = adjustcolor("white", alpha = 0),
      ylim = c(0.0002,100), xlim = c(1/300, 0.5),
      ylab = "",
      xaxt = 'n',
      yaxt = "n",
      xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)

models = c("ECHAM5","GISS", "CESM","HadCM3", "isoGSM")
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.2
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.1
  LLines(spec_ratio, col = adjustcolor(COLZ[ii], alpha.f = 0.2), lty = 1, lw = 2)
}
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.2
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.1
  LLines(LogSmooth(spec_ratio), col = COLZ[ii], lty = 1, lw = lw_smooth)
}

mtext(TeX("b) $\\delta^{18}$O$_{speleo}$/$\\delta^{18}$O$_{sim}$ (annual resolution)"), side = 3, line = -3, adj = 0.05, cex = cex_text)

#c) second plot is spec ratio between speleo-d18O and downsampled d18O
LPlot(spec_ratio, col = adjustcolor("white", alpha = 0),
      ylim = c(0.0002,100), xlim = c(1/300, 0.5),
      ylab = "",
      xaxt = 'n',
      yaxt = "n",
      xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext(expression("PSD ratio"), side = 4, line= 2.5, at = 1, las = 0, cex = cex_axis_text)
mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)
axis(side = 4, at = c(1e-3,1e-2, 1e-1,1, 1e1, 1e2), labels = FALSE)
mtext(side=4,at=c(1e-3,1e-2, 1e-1,1, 1e1, 1e2),line = 1, c(1e-3,1e-2, 0.1,1, 10, 100),las=1,col="black", cex = cex_axis)

models = c("ECHAM5","GISS", "CESM","HadCM3", "isoGSM")
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$lim.2
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$lim.1
  LLines(spec_ratio, col = adjustcolor(COLZ[ii], alpha.f = 0.2), lty = 1, lw = 2)
}
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$lim.2
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$DOWN[[models[ii]]][[variable]]$Mean$spec$lim.1
  LLines(LogSmooth(spec_ratio), col = COLZ[ii], lty = 1, lw = lw_smooth)
}

legend("bottomleft", legend = c("ECHAM5-wiso","GISS-E2-R", "iCESM","iHadCM3", "isoGSM"),
       text.col = COLZ, 
       bty = "n", cex = cex_text_legend)

mtext(TeX("c) $\\delta^{18}$O$_{speleo}$/$\\delta^{18}$O$_{sim}$ (record resolution)"), side = 3, line = -3, adj = 0.05, cex = cex_text)


#d) inset in first plot:
par(fig = c(0.1,0.32, 0.1, 0.5), new = T)  

plot(NULL, ylim = c(0,1.3), xlim = c(log10(0.005), log10(20)), xlab = "",xaxt = 'n',
     main = "", cex.main = cex_text, cex.axis = cex_text*1.5, bg = "white")
rect(par('usr')[1], par('usr')[3], par('usr')[2], par('usr')[4], col = "white")

mtext("  d) Variance speleo-isotopes", side = 3, line = -2, adj = 0.05, cex = cex_text)

axis(side = 1, at = c(log10(0.01), log10(0.1), 0, log10(10)),
     labels = c(0.01, 0.1, 1, 10), cex.axis = cex_text*1.5)
mtext("‰^2", side = 1, line= 2, cex = cex_axis_text)
lines(c(median(log10(VARIANCE$d18O), na.rm = T),median(log10(VARIANCE$d18O), na.rm = T)),
      c(0, max(density(log10(VARIANCE$d18O), na.rm = T)$y)-0.01),
      lwd = 2, col = "#B2182B", lty = 2)
lines(density(log10(VARIANCE$d18O), na.rm = T),
      lwd = 2, col = "#B2182B")
lines(c(median(log10(VARIANCE$d13C), na.rm = T),median(log10(VARIANCE$d13C), na.rm = T)),
      c(0, max(density(log10(VARIANCE$d13C), na.rm = T)$y)-0.01),
      lwd = 2, col = COLZ_carbon, lty = 2)
lines(density(log10(VARIANCE$d13C),na.rm = T),
      lwd = 2, col = COLZ_carbon)
abline(v=c(log10(0.01), log10(0.1), 0, log10(10)), col=COLZ_grid, lty=2)
mtext(text = "density",side = 2,line = 2.5, cex = cex_text)
mtext(text = expression(paste(delta^{plain(18)}, plain(O))), side = 3, line = -4, adj = 1,col = "#B2182B", cex = cex_text, at = log10(5))
mtext(text = expression(paste(delta^{plain(13)}, plain(C))), side = 3, line = -6.5, adj = 1,col = COLZ_carbon, cex = cex_text, at = log10(5))
box(col = "black")

dev.off()
```

```{r}
No.digits = 2

bstrap_tuned <- c()
for (i in 1:1000){
  bstrap_tuned <- c(bstrap_tuned,median(sample(VARIANCE$d13C,length(VARIANCE$d13C),replace=T), na.rm = T))
}

print(paste0("Median d13C : ", round(median(as.numeric(VARIANCE$d13C), na.rm = T),digits = No.digits), "[‰^2],",
                 " 90% CI: (", round(quantile(bstrap_tuned,0.05), digits = No.digits), ", ", round(quantile(bstrap_tuned,0.95), digits = No.digits), ")"))

bstrap_tuned <- c()
for (i in 1:1000){
  bstrap_tuned <- c(bstrap_tuned,median(sample(VARIANCE$d18O,length(VARIANCE$d18O),replace=T), na.rm = T))
}

print(paste0("Median d18O : ", round(median(as.numeric(VARIANCE$d18O), na.rm = T),digits = No.digits), "[‰^2],",
                 " 90% CI: (", round(quantile(bstrap_tuned,0.05), digits = No.digits), ", ", round(quantile(bstrap_tuned,0.95), digits = No.digits), ")"))
  

```


Some numbers:
How many speleothems have significant trends in the data?
```{r}
trend_d18O <- list(entity_id = c(), trend = c(), p.value = c(), c.0025 = c(), c.0975 = c())
trend_d13C <- list(entity_id = c(), trend = c(), p.value = c(), c.0025 = c(), c.0975 = c())
for(entity in ENTITY_INFO$entity_id){
  data = DOWN$HadCM3 %>% filter(entity_id == entity)
  
  if(!all(is.na(data$d13C_measurement))){
    
    tmp <- lm(data$d18O_measurement*1000 ~ data$year_BP)
    trend_d18O$entity_id = c(trend_d18O$entity_id, entity)
    trend_d18O$trend = c(trend_d18O$trend, summary(tmp)$coefficients[[2]])
    trend_d18O$p.value = c(trend_d18O$p.value, summary(tmp)$coefficients[[8]])
    trend_d18O$c.0025 = c(trend_d18O$c.0025, confint(tmp)[[2]])
    trend_d18O$c.0975 = c(trend_d18O$c.0975, confint(tmp)[[4]])
    
    tmp <- lm(data$d13C_measurement*1000 ~ data$year_BP)
    trend_d13C$entity_id = c(trend_d13C$entity_id, entity)
    trend_d13C$trend = c(trend_d13C$trend, summary(tmp)$coefficients[[2]])
    trend_d13C$p.value = c(trend_d13C$p.value, summary(tmp)$coefficients[[8]])
    trend_d13C$c.0025 = c(trend_d13C$c.0025, confint(tmp)[[2]])
    trend_d13C$c.0975 = c(trend_d13C$c.0975, confint(tmp)[[4]])
  }
  
  
}

print(paste(round(100*sum((trend_d18O$c.0025>0 | trend_d18O$c.0975< 0)&trend_d18O$p.value<0.05)/length(trend_d18O$entity_id), digits = 3),"% of d18O show a trend."))
print(paste("Absolute change for 1000y: +-",round(mean(abs(trend_d18O$trend)[(trend_d18O$c.0025>0 | trend_d18O$c.0975< 0)&trend_d18O$p.value<0.05]), digits = 3),"permil"))
print(paste(round(100*sum((trend_d13C$c.0025>0 | trend_d13C$c.0975< 0)&trend_d13C$p.value<0.05)/length(trend_d13C$entity_id), digits = 3),"% of d13C show a trend."))
print(paste("Absolute change for 1000y: +-",round(mean(abs(trend_d13C$trend)[(trend_d13C$c.0025>0 | trend_d13C$c.0975< 0)&trend_d13C$p.value<0.05]), digits = 3),"permil"))

```

```{r}
rm(var)

#VARIANCE <- list()
for(Model in c("HadCM3", "ECHAM5", "GISS", "CESM", "isoGSM")){
  #fields::image.plot(VAR_FIELDS[[Model]], zlim = c(0,100))
  VARIANCE[[Model]] <- list(FULL = list(), FULL_300 = list(), FULL_SPEC = list(), DOWN = list(), DOWN_SPEC = list(), REC = list(), REC_SPEC = list())
  for(entity in ENTITY_INFO$entity_id){
    if(entity %in% c(278,598,672,378)){next}
    if(entity == 33 & Model == "GISS"){next}
    data_full = FULL[[Model]] %>% filter(entity_id == entity)
    data_rec = DOWN[[Model]] %>% filter(entity_id == entity)
    if(all(is.na(data_rec$d13C_measurement))){next}
    
    VARIANCE[[Model]]$FULL = c(VARIANCE[[Model]]$FULL, var(data_full$ITIF, na.rm = T))
    VARIANCE[[Model]]$DOWN = c(VARIANCE[[Model]]$DOWN, var(data_rec$ITIF, na.rm = T))
    VARIANCE[[Model]]$REC = c(VARIANCE[[Model]]$REC, var(data_rec$d18O_measurement, na.rm = T))
    
    VARIANCE[[Model]]$entity_id = c(VARIANCE[[Model]]$entity_id, entity)
    
  }
  VARIANCE[[Model]]$FULL = as.numeric(VARIANCE[[Model]]$FULL)
  VARIANCE[[Model]]$DOWN = as.numeric(VARIANCE[[Model]]$DOWN)
  VARIANCE[[Model]]$REC = as.numeric(VARIANCE[[Model]]$REC)
  VARIANCE[[Model]]$entity_id = as.numeric(VARIANCE[[Model]]$entity_id)
}


```
```{r}
source("Functions/aw_mean.R")
VAR_FIELDS<-list()
load("DATA/SISAL1k_VarField_HadCM3.RData")
VAR_FIELDS$HadCM3 <- MEAN_FIELD$ITIF
load("DATA/SISAL1k_VarField_ECHAM5.RData")
VAR_FIELDS$ECHAM5 <- MEAN_FIELD$ITIF
load("DATA/SISAL1k_VarField_GISS.RData")
VAR_FIELDS$GISS <- MEAN_FIELD$ITIF
load("DATA/SISAL1k_VarField_CESM.RData")
VAR_FIELDS$CESM <- MEAN_FIELD$ITIF
load("DATA/SISAL1k_VarField_isoGSM.RData")
VAR_FIELDS$isoGSM <- MEAN_FIELD$ITIF

VAR_FIELDS$HadCM3[VAR_FIELDS$HadCM3>50] = NA
VAR_FIELDS$ECHAM5[VAR_FIELDS$ECHAM5>50] = NA
VAR_FIELDS$GISS[VAR_FIELDS$GISS>50] = NA
VAR_FIELDS$CESM[VAR_FIELDS$CESM>50] = NA
VAR_FIELDS$isoGSM[VAR_FIELDS$isoGSM>50] = NA



No.digits = 2

exp_var_global = c("$var_{\text{global}}$")
exp_var_speleo_full = c("$var_{\text{speleo}}$ (annual)")
exp_var_speleo_ds = c("$var_{\text{speleo}}$ (down-sampled)")

for(Model in c("ECHAM5", "GISS", "CESM", "HadCM3", "isoGSM")){
  print(paste(Model,":", round(simpleawmean(VAR_FIELDS[[Model]], lats = seq(-90,90,length.out = dim(VAR_FIELDS[[Model]])[2])), digits = No.digits),
              "90% CI: (",round(quantile(as.numeric(VAR_FIELDS[[Model]]), probs = 0.05, na.rm = T),digits = No.digits),",",
              round(quantile(as.numeric(VAR_FIELDS[[Model]]), probs = 0.95, na.rm = T),digits = No.digits),")"))
  
  exp_var_global = c(exp_var_global, paste0("& ",round(simpleawmean(VAR_FIELDS[[Model]], 
                                                                    lats = seq(-90,90,length.out = dim(VAR_FIELDS[[Model]])[2])), 
                                                       digits = No.digits)," (",
                                            round(quantile(as.numeric(VAR_FIELDS[[Model]]), probs = 0.05, na.rm = T),digits = No.digits), ", ",
                                            round(quantile(as.numeric(VAR_FIELDS[[Model]]), probs = 0.95, na.rm = T),digits = No.digits),")"))
  
  print(paste("Annual resolution at speleo location",Model,":", round(median(as.numeric(VARIANCE[[Model]]$FULL), na.rm = T), digits = No.digits),
            "90% CI: (",round(quantile(as.numeric(VARIANCE[[Model]]$FULL), probs = 0.05, na.rm = T), digits = No.digits),
            ",",round(quantile(as.numeric(VARIANCE[[Model]]$FULL), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
  exp_var_speleo_full = c(exp_var_speleo_full, paste0("& ", round(median(as.numeric(VARIANCE[[Model]]$FULL), na.rm = T), digits = No.digits), " (",
                                                      round(quantile(as.numeric(VARIANCE[[Model]]$FULL), probs = 0.05, na.rm = T), digits = No.digits),", ",
                                                      round(quantile(as.numeric(VARIANCE[[Model]]$FULL), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
  print(paste("Record resolution at speleo location",Model,":", round(median(as.numeric(VARIANCE[[Model]]$DOWN), na.rm = T), digits = No.digits),
            "90% CI: (",round(quantile(as.numeric(VARIANCE[[Model]]$DOWN), probs = 0.05, na.rm = T), digits = No.digits),
            ",",round(quantile(as.numeric(VARIANCE[[Model]]$DOWN), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
  exp_var_speleo_ds = c(exp_var_speleo_ds, paste0("& ", round(median(as.numeric(VARIANCE[[Model]]$DOWN), na.rm = T), digits = No.digits), " (",
                                                  round(quantile(as.numeric(VARIANCE[[Model]]$DOWN), probs = 0.05, na.rm = T), digits = No.digits),", ",
                                                  round(quantile(as.numeric(VARIANCE[[Model]]$DOWN), probs = 0.95, na.rm = T), digits = No.digits),")"))
}

 print(paste0(exp_var_global[[1]], exp_var_global[[2]],exp_var_global[[3]],exp_var_global[[4]],exp_var_global[[5]],exp_var_global[[6]], "\\"))
 print(paste0(exp_var_speleo_full[[1]],exp_var_speleo_full[[2]],exp_var_speleo_full[[3]],exp_var_speleo_full[[4]],exp_var_speleo_full[[5]],exp_var_speleo_full[[6]], "\\"))
 print(paste0(exp_var_speleo_ds[[1]],exp_var_speleo_ds[[2]],exp_var_speleo_ds[[3]],exp_var_speleo_ds[[4]],exp_var_speleo_ds[[5]],exp_var_speleo_ds[[6]], " \\"))
```




```{r}
hist(VAR_FIELDS$HadCM3, breaks = 9, border = "white", prob = TRUE, 
     ylim = c(0,3), xlim = c(0,10), xlab = "", ylab = "", main = "", cex.main = cex_text, cex.axis = cex_text)


lines(density(as.numeric(VARIANCE$HadCM3$FULL), na.rm = T), lwd = 2, col = RColorBrewer::brewer.pal(6,"Reds")[6])
lines(density(as.numeric(VARIANCE$ECHAM5$FULL), na.rm = T), lwd = 2, col = RColorBrewer::brewer.pal(6,"Reds")[5])
lines(density(as.numeric(VARIANCE$GISS$FULL), na.rm = T), lwd = 2, col = RColorBrewer::brewer.pal(6,"Reds")[4])
lines(density(as.numeric(VARIANCE$CESM$FULL), na.rm = T), lwd = 2, col = RColorBrewer::brewer.pal(6,"Reds")[3])
lines(density(as.numeric(VARIANCE$isoGSM$FULL), na.rm = T), lwd = 2, col = RColorBrewer::brewer.pal(6,"Reds")[2])

```

Now comes the plotting. Let's see what we are left with...


Here with the filter:
```{r}
cex_text = 1.2
cex_text_legend = 1.9
cex_axis = 1
cex_axis_text = 1
lw_smooth =3

cairo_pdf(file = paste0("Plots/Supplement/SFig_9_Spectra_Filter.pdf"), width = 10/2*3, height = 6)

COLZ = c(rgb(112,160,205, max = 255), rgb(0,52,102, max = 255), rgb(178,178,178, max = 255),rgb(0,121,0, max = 255), rgb(196,121,0, max = 255))

COLZ_carbon = "black"
COLZ_grid = adjustcolor("grey", alpha.f = 0.5)

#########################################################################################################
par(mar=c(1,2,0,1),oma=c(3,3,3,3),xaxs="i",yaxs="i",cex=1,lwd=2, mfrow = c(1,3))

spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$RECD$d13C$Mean$spec$spec
spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$RECD$d13C$Mean$spec$lim.1
spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$RECD$d13C$Mean$spec$lim.2
LPlot(spec_ratio, col = "white",
        ylim = c(0.0002,100), xlim = c(1/300, 0.5),
        ylab = "",
        xaxt = 'n',
        yaxt = "n",
        xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
mtext(expression("PSD ratio"), side = 2, line= 2, at = 1, las = 0, cex = cex_axis_text)

axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)
axis(side=2, at = c(1e-3, 1e-1, 1e1, 1e3), labels = FALSE)
mtext(side=2,at=c(1e-3, 1e-1, 1e1, 1e3),line = 1, c(1e-3, 0.1, 10, 1000),las=1,col="black", cex = cex_axis)

LLines(spec_ratio, col = adjustcolor("black", alpha.f = 0.3), lty = 1, lw = 2)
LLines(LogSmooth(spec_ratio), col = "black", lw = lw_smooth)

mtext(TeX("a) $\\delta^{18}$O$_{speleo}$/$\\delta^{13}$C$_{speleo}"), side = 3, line = -3, adj = 0.05, cex = cex_text)

###############################################################################################

#b) second plot is spec ratio between speleo-d18O and annual d18O
LPlot(spec_ratio, col = adjustcolor("white", alpha = 0),
      ylim = c(0.0002,100), xlim = c(1/300, 0.5),
      ylab = "",
      xaxt = 'n',
      yaxt = "n",
      xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
#mtext(expression("PSD ratio"), side = 4, line= 2.5, at = 1, las = 0, cex = cex_axis_text)

axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)
#axis(side = 4, at = c(1e-3,1e-2, 1e-1,1, 1e1, 1e2), labels = FALSE)
#mtext(side=4,at=c(1e-3,1e-2, 1e-1,1, 1e1, 1e2),line = 1, c(1e-3,1e-2, 0.1,1, 10, 100),las=1,col="black", cex = cex_axis)

models = c("ECHAM5","GISS", "CESM","HadCM3", "isoGSM")
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.1
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.2
  LLines(spec_ratio, col = adjustcolor(COLZ[ii], alpha.f = 0.2), lty = 1, lw = 2)
}
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.1
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$FULL[[models[ii]]][[variable]]$Mean$spec$lim.2
  LLines(LogSmooth(spec_ratio), col = COLZ[ii], lty = 1, lw = lw_smooth)
}

mtext(TeX("b) $\\delta^{18}$O$_{speleo}$/$\\delta^{18}$O$_{sim}$ (annual resolution)"), side = 3, line = -3, adj = 0.05, cex = cex_text)

###############################################################################################

#c) second plot is spec ratio between speleo-d18O and downsampled d18O
LPlot(spec_ratio, col = adjustcolor("white", alpha = 0),
      ylim = c(0.0002,100), xlim = c(1/300, 0.5),
      ylab = "",
      xaxt = 'n',
      yaxt = "n",
      xlab = "", lwd = 2)
abline(h=c(1e-3, 1e-2, 1e-1, 1e1, 1e2, 1e3), v=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), col=COLZ_grid, lty=3)
abline(h=1)

mtext("Period (y)", side = 1, line= 2, cex = cex_axis_text)
mtext(expression("PSD ratio"), side = 4, line= 2.5, at = 1, las = 0, cex = cex_axis_text)

axis(side = 1, at = c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5), labels = FALSE)
mtext(side=1,at=c(0.005, 0.01, 0.02, 0.05,0.1, 0.2, 0.5),line = 1,
      c(1/0.005, 1/0.01, 1/0.02, 1/0.05,1/0.1, 1/0.2, 1/0.5),las=1,col="black", cex = cex_axis)
axis(side = 4, at = c(1e-3,1e-2, 1e-1,1, 1e1, 1e2), labels = FALSE)
mtext(side=4,at=c(1e-3,1e-2, 1e-1,1, 1e1, 1e2),line = 1, c(1e-3,1e-2, 0.1,1, 10, 100),las=1,col="black", cex = cex_axis)

models = c("ECHAM5","GISS", "CESM","HadCM3", "isoGSM")
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$lim.1
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$lim.2
  LLines(spec_ratio, col = adjustcolor(COLZ[ii], alpha.f = 0.2), lty = 1, lw = 2)
}
for(ii in 1:5){
  variable = "ITIF"
  spec_ratio <- SPECTRA$RECD$d18O$Mean$spec
  spec_ratio$spec <- SPECTRA$RECD$d18O$Mean$spec$spec/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$spec
  spec_ratio$lim.1 <- SPECTRA$RECD$d18O$Mean$spec$lim.1/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$lim.1
  spec_ratio$lim.2 <- SPECTRA$RECD$d18O$Mean$spec$lim.2/SPECTRA$DOWN_FILTER[[models[ii]]][[variable]]$Mean$spec$lim.2
  LLines(LogSmooth(spec_ratio), col = COLZ[ii], lty = 1, lw = lw_smooth)
}

legend("bottomleft", legend = c("ECHAM5-wiso","GISS-E2-R", "iCESM","iHadCM3", "isoGSM"),
       text.col = COLZ, 
       bty = "n", cex = cex_text_legend)

mtext(TeX("c) $\\delta^{18}$O$_{speleo}$/$\\delta^{18}$O$_{sim}$ (record resolution)"), side = 3, line = -3, adj = 0.05, cex = cex_text)
mtext(" FILTERED 2.5y", side = 3, line = -5, adj = 0.05, cex = cex_text)

###############################################################################################

#d) inset in first plot:
par(fig = c(0.1,0.32, 0.1, 0.5), new = T)  

plot(NULL, ylim = c(0,1.3), xlim = c(log10(0.005), log10(20)), xlab = "",xaxt = 'n',
     main = "", cex.main = cex_text, cex.axis = cex_text*1.5, bg = "white")
rect(par('usr')[1], par('usr')[3], par('usr')[2], par('usr')[4], col = "white")

mtext("  d) Variance speleo-isotopes", side = 3, line = -2, adj = 0.05, cex = cex_text)

axis(side = 1, at = c(log10(0.01), log10(0.1), 0, log10(10)),
     labels = c(0.01, 0.1, 1, 10), cex.axis = cex_text*1.5)
mtext("‰^2", side = 1, line= 2, cex = cex_axis_text)
lines(c(median(log10(VARIANCE$d18O), na.rm = T),median(log10(VARIANCE$d18O), na.rm = T)),
      c(0, max(density(log10(VARIANCE$d18O), na.rm = T)$y)-0.01),
      lwd = 2, col = "#B2182B", lty = 2)
lines(density(log10(VARIANCE$d18O), na.rm = T),
      lwd = 2, col = "#B2182B")
lines(c(median(log10(VARIANCE$d13C), na.rm = T),median(log10(VARIANCE$d13C), na.rm = T)),
      c(0, max(density(log10(VARIANCE$d13C), na.rm = T)$y)-0.01),
      lwd = 2, col = COLZ_carbon, lty = 2)
lines(density(log10(VARIANCE$d13C),na.rm = T),
      lwd = 2, col = COLZ_carbon)
abline(v=c(log10(0.01), log10(0.1), 0, log10(10)), col=COLZ_grid, lty=2)

mtext(text = "density",side = 2,line = 2.5, cex = cex_text)
mtext(text = expression(paste(delta^{plain(18)}, plain(O))), side = 3, line = -4, adj = 1,col = "#B2182B", cex = cex_text, at = log10(5))
mtext(text = expression(paste(delta^{plain(13)}, plain(C))), side = 3, line = -6.5, adj = 1,col = COLZ_carbon, cex = cex_text, at = log10(5))
box(col = "black")

dev.off()

```
