---
title: "Review1Figures"
author: "Janica Bühler"
date: "18 1 2022"
output: html_document
---
# 1 Plot is correlation of temperature to ISOT and to ITIF and a diff plot between the two

```{r message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(tidyverse)
library(latex2exp)
library(zoo)
library(nest)
library(PaleoSpec)
source("Functions/STACYmap_PMIL_NAgrid_discrete.R")
```

```{r}
var= "PREC"

source("Functions/downsample_field.R")
CORR_FIELDS <- list()
load("DATA/SISAL1k_CorrField_HadCM3.RData")
CORR_FIELDS$HadCM3$ITIF <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$HadCM3$ITIF_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)
load("DATA/SISAL1k_CorrField_ISOT_HadCM3.RData")
CORR_FIELDS$HadCM3$ISOT <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$HadCM3$ISOT_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)

load("DATA/SISAL1k_CorrField_ECHAM5.RData")
CORR_FIELDS$ECHAM5$ITIF <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$ECHAM5$ITIF_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)
load("DATA/SISAL1k_CorrField_ISOT_ECHAM5.RData")
CORR_FIELDS$ECHAM5$ISOT <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$ECHAM5$ISOT_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)

load("DATA/SISAL1k_CorrField_GISS.RData")
CORR_FIELDS$GISS$ITIF <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$GISS$ITIF_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)
load("DATA/SISAL1k_CorrField_ISOT_GISS.RData")
CORR_FIELDS$GISS$ISOT <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$GISS$ISOT_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)

load("DATA/SISAL1k_CorrField_CESM.RData")
CORR_FIELDS$CESM$ITIF <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$CESM$ITIF_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)
load("DATA/SISAL1k_CorrField_ISOT_CESM.RData")
CORR_FIELDS$CESM$ISOT <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$CESM$ISOT_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)

load("DATA/SISAL1k_CorrField_isoGSM.RData")
CORR_FIELDS$isoGSM$ITIF <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$isoGSM$ITIF_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)
load("DATA/SISAL1k_CorrField_ISOT_isoGSM.RData")
CORR_FIELDS$isoGSM$ISOT <- downsample_field(CORR_FIELD[[var]], 96, 48)
CORR_FIELDS$isoGSM$ISOT_P <- downsample_field(CORR_FIELD[[paste0(var,"_P")]], 96, 48)

Model_list = c("HadCM3", "ECHAM5", "GISS", "isoGSM", "CESM")

MEAN_FIELD = list(ISOT = array(dim = c(96,48)), ITIF = array(dim = c(96,48)))
AGREE = list(ISOT = array(dim = c(96,48), data = 0), ITIF = array(dim = c(96,48), data = 0))

for(lon in 1:96){
  for(lat in 1:48){
    for(VAR in c("ISOT", "ITIF")){
      tmp_list = c(CORR_FIELDS$HadCM3[[VAR]][lon,lat],
                 CORR_FIELDS$ECHAM5[[VAR]][lon,lat],
                 CORR_FIELDS$isoGSM[[VAR]][lon,lat],
                 CORR_FIELDS$CESM[[VAR]][lon,lat],
                 CORR_FIELDS$GISS[[VAR]][lon,lat])
      p_list = c(CORR_FIELDS$HadCM3[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$ECHAM5[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$isoGSM[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$CESM[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$GISS[[paste0(VAR,"_P")]][lon,lat])
    tmp_list[p_list>0.1] = NA
    MEAN_FIELD[[VAR]][lon,lat] = mean(tmp_list, na.rm = T)
    if(sum(is.na(tmp_list))>3){MEAN_FIELD[[VAR]][lon,lat] = NA}
    }
  }
}


for(Model in Model_list){
  for(lon in 1:96){
    for(lat in 1:48){
      if(!is.na(MEAN_FIELD$ISOT[lon,lat]) & !is.na(CORR_FIELDS[[Model]]$ISOT[lon,lat])){
        if(sign(MEAN_FIELD$ISOT[lon,lat]) == sign(CORR_FIELDS[[Model]]$ISOT[lon,lat])){AGREE$ISOT[lon,lat] = AGREE$ISOT[lon,lat]+1}
      }
      if(!is.na(MEAN_FIELD$ITIF[lon,lat]) & !is.na(CORR_FIELDS[[Model]]$ITIF[lon,lat])){
       if(sign(MEAN_FIELD$ITIF[lon,lat]) == sign(CORR_FIELDS[[Model]]$ITIF[lon,lat])){AGREE$ITIF[lon,lat] = AGREE$ITIF[lon,lat]+1} 
      }
    }
  }
}

```


Plot:
```{r}
plots <- list()
for(var in c("ISOT", "ITIF", "DIFF")){
  if(var == "DIFF"){
    Plot_lyr = MEAN_FIELD$ISOT - MEAN_FIELD$ITIF
  }else{
    Plot_lyr = MEAN_FIELD[[var]]
  }
  
  GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE <- 3
  NA_plot_lyr = Plot_lyr
  NA_plot_lyr[!is.na(NA_plot_lyr)] = 0
  NA_plot_lyr[is.na(NA_plot_lyr)] = 1
  if(var == "DIFF"){
   Plot_lyr[1,1] = 2
   Plot_lyr[1,2] = -2
  }else{
    Plot_lyr[1,1] = 1
    Plot_lyr[1,2] = -1
  }
  
  leg_name = TeX("$\\rho (P, \\delta^{18}O)$")
  if(var == "ITIF"){leg_name = TeX("$\\rho (P, \\delta^{18}O_{iw})$")}
  if(var == "DIFF"){leg_name = TeX("$\\rho (P, \\delta^{18}O) - \\rho (P, \\delta^{18}O_{iw})$")}

  if(var == "DIFF"){
    plot = STACYmap_NA(gridlyr = rbind(Plot_lyr[49:96,],Plot_lyr[1:48,]), graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = rbind(NA_plot_lyr[49:96],NA_plot_lyr[1:48,]), NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-2", "", "","", "-1", "", "", "", "0", "","", "", "1", "", "", "", "2"), 
                                                discrete_breaks = seq(-2,2,length.out = 17))
  }else{
    plot = STACYmap_NA(gridlyr = rbind(Plot_lyr[49:96,],Plot_lyr[1:48,]), graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = rbind(NA_plot_lyr[49:96],NA_plot_lyr[1:48,]), NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-1", "", "", "-0.5", "", "", "0", "", "", "0.5", "", "", "1"), 
                                                discrete_breaks = seq(-1,1,length.out = 13))
  } 
  
  plots[[paste0(var,"_agree")]] = plot + theme(panel.border = element_blank(),
          legend.background = element_blank(),
          axis.text = element_blank(),
          text = element_text(size = 12),
          legend.title = element_text(size = 12))

  
}

plot <- ggpubr::ggarrange(plots$ISOT_agree, plots$ITIF_agree, plots$DIFF_agree, labels = c("a)", "b)", "c)"), ncol = 3, nrow = 1)
plot  %>% ggsave(filename = paste0('RevFig_1_CorrelationMap_ISOTvsITIF_PREC.pdf'), plot = ., path = 'Plots', 
                 width = 3*10, height = 1*8, units = 'cm', dpi = 'print', device = "pdf")
plot  %>% ggsave(filename = paste0('RevFig_1_CorrelationMap_ISOTvsITIF_PREC.png'), plot = ., path = 'Plots', 
                 width = 3*10, height = 1*8, units = 'cm', dpi = 'print', device = "png")
```

# 2 is an evaporation map of all Simulations

```{r}
source("Functions/aw_mean.R")
#HadCM3
load("DATA/SISAL1k_MeanField_HadCM3.RData")
isot_lyr_HadCM3 <- MEAN_FIELD$EVAP
isot_GM_HadCM3 <- simpleawmean(apply(MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE))
#ECHAM5
load("DATA/SISAL1k_MeanField_ECHAM5.RData")
isot_lyr_ECHAM5 <- MEAN_FIELD$EVAP
isot_GM_ECHAM5 <- simpleawmean(apply(MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 48))
#CESM
load("DATA/SISAL1k_MeanField_CESM.RData")
isot_lyr_CESM <- MEAN_FIELD$EVAP[,96:1]
isot_GM_CESM <- simpleawmean(apply(MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 96))
#GISS
load("DATA/SISAL1k_MeanField_GISS.RData")
isot_lyr_GISS <- MEAN_FIELD$EVAP
isot_GM_GISS <- simpleawmean(apply(MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 90))
#isoGSM
load("DATA/SISAL1k_MeanField_isoGSM.RData")
isot_lyr_isoGSM <- MEAN_FIELD$EVAP[,]
isot_GM_isoGSM <- simpleawmean(apply(MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 94))
rm(MEAN_FIELD)
```
Range Layer:
## Range Layer:
```{r}
library(nest)
library(PaleoSpec)
source("Functions/downsample_field.R")
source("Functions/aw_mean.R")
isot_lyr_HadCM3_ds <- downsample_field(isot_lyr_HadCM3, 96, 48)
isot_lyr_ECHAM5_ds <- downsample_field(isot_lyr_ECHAM5, 96, 48)
isot_lyr_isoGSM_ds   <- downsample_field(isot_lyr_isoGSM,   96, 48)
isot_lyr_GISS_ds   <- downsample_field(isot_lyr_GISS,   96, 48)
isot_lyr_CESM_ds   <- downsample_field(isot_lyr_CESM,   96, 48)

mean_lyr = (isot_lyr_HadCM3_ds + isot_lyr_ECHAM5_ds + isot_lyr_isoGSM_ds + isot_lyr_GISS_ds + isot_lyr_CESM_ds)/5

GM_HadCM3 = simpleawmean(isot_lyr_HadCM3_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_ECHAM5 = simpleawmean(isot_lyr_ECHAM5_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_isoGSM = simpleawmean(isot_lyr_isoGSM_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_GISS = simpleawmean(isot_lyr_GISS_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_CESM = simpleawmean(isot_lyr_CESM_ds, lats = seq(from = -90, to = 90, length.out = 48))

isot_lyr_diff <- array(dim = c(96, 48))
isot_lyr_diff_withoutmean <- array(dim = c(96, 48))
for(ii in 1:96){
  for(jj in 1:48){
    isot_lyr_diff[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj], 
                                        isot_lyr_ECHAM5_ds[ii,jj], 
                                        isot_lyr_isoGSM_ds[ii,jj], 
                                        isot_lyr_GISS_ds[ii,jj], 
                                        isot_lyr_CESM_ds[ii,jj]), na.rm = T), na.rm = T)
    
    isot_lyr_diff_withoutmean[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj]-GM_HadCM3, 
                                                    isot_lyr_ECHAM5_ds[ii,jj]-GM_ECHAM5, 
                                                    isot_lyr_isoGSM_ds[ii,jj]-GM_isoGSM, 
                                                    isot_lyr_GISS_ds[ii,jj]-GM_GISS, 
                                                    isot_lyr_CESM_ds[ii,jj]-GM_CESM), na.rm = T), na.rm = T)
  }
}

rm(ii,jj)
```

```{r pressure, echo=FALSE, warning=FALSE}
source("Functions/STACYmap_PMIL_discrete.R")

plot_HadCM3 <- STACYmap_discrete(rbind((isot_lyr_HadCM3)[49:96,],(isot_lyr_HadCM3)[1:48,]),
                                 legend_name = list(grid = "E (mm/year)"), graticules = T, colorscheme = "prcp_grd", 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","","",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,by = 500)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("iHadCM3, GM: ",round(simpleawmean(isot_lyr_HadCM3), digits = 1), "mm/year"))

#plot_HadCM3

plot_ECHAM5 <- STACYmap_discrete(rbind(isot_lyr_ECHAM5[49:96,1:48],isot_lyr_ECHAM5[1:48,1:48]),
                                 legend_name = list(grid = "E (mm/year)"), graticules = T, colorscheme = "prcp_grd", 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","","",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,by = 500)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("ECHAM5-wiso, GM: ",round(simpleawmean(isot_lyr_ECHAM5, lats = seq(from = -90,to = 90,length.out = 48)), digits = 1), "mm/year"))

#plot_ECHAM5

plot_isoGSM <- STACYmap_discrete(rbind(isot_lyr_isoGSM[97:192,1:94],isot_lyr_isoGSM[1:96,1:94]),
                                 legend_name = list(grid = "E (mm/year)"), graticules = T, colorscheme = "prcp_grd", 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","","",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,by = 500)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("isoGSM, GM: ",round(simpleawmean(isot_lyr_isoGSM, lats = seq(from = -90,to = 90,length.out = 96)), digits = 1), "mm/year"))
  

#plot_CCSM

plot_GISS <- STACYmap_discrete(rbind(isot_lyr_GISS[73:144,1:90],isot_lyr_GISS[1:72,1:90]),
                               legend_name = list(grid = "E (mm/year)"), graticules = T, colorscheme = "prcp_grd", 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","","",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,by = 500)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("GISS-E2-R, GM: ",round(simpleawmean(isot_lyr_GISS, lats = seq(from = -90,to = 90,length.out = 90)), digits = 1), "mm/year"))

#plot_GISS

plot_CESM <- STACYmap_discrete(rbind(isot_lyr_CESM[73:144,1:96],isot_lyr_CESM[1:72,1:96]),
                               legend_name = list(grid = "E (mm/year)"), graticules = T, colorscheme = "prcp_grd", 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","","",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,by = 500)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("CESM, GM: ",round(simpleawmean(isot_lyr_CESM, lats = seq(from = -90,to = 90,length.out = 94)), digits = 1), "mm/year"))
  


  Plot_lyr = rbind(isot_lyr_diff[49:96,1:48],isot_lyr_diff[1:48,1:48])
  #Plot_lyr[Plot_lyr>25] = NA
  
  plot_diff <- STACYmap_discrete(gridlyr =  Plot_lyr, 
                                 legend_names = list(grid = "E range (mm/year)"), graticules = T, 
                                 colorscheme = RColorBrewer::brewer.pal(9, 'Reds'), 
                                 limits_color = list("max" = 2000, "min" = 0),
                                 labels_discrete = c(0,"","","",1000,"","","",2000), 
                                 discrete_breaks = seq(0,2000,by = 250)) +
    theme(panel.border = element_blank(), legend.background = element_blank(), 
          axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
    ggtitle("E range (mm/year)")



#plot_diff

library(ggpubr)
plot <- ggarrange(plot_ECHAM5, plot_GISS, plot_CESM, plot_HadCM3, plot_isoGSM, plot_diff,
                  labels = c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)"),
                  ncol = 3, nrow = 2)

#plot
  plot  %>% ggsave(filename = "Plots/RevFig_2_SimOverview_EVAP.pdf", plot = .,
                 width = 3*12, height = 2*8.3, units = 'cm', dpi = 'print', device = "pdf")
  plot  %>% ggsave(filename = "Plots/RevFig_2_SimOverview_EVAP.png", plot = ., 
                 width = 36, height = 16, units = 'cm', dpi = 'print', device = "png")

plot
```

# 2 is an evaporation map of all Simulations

```{r}
source("Functions/aw_mean.R")
#HadCM3
load("DATA/SISAL1k_MeanField_HadCM3.RData")
isot_lyr_HadCM3 <- MEAN_FIELD$PREC -MEAN_FIELD$EVAP
isot_GM_HadCM3 <- simpleawmean(apply(MEAN_FIELD$PREC - MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE))
#ECHAM5
load("DATA/SISAL1k_MeanField_ECHAM5.RData")
isot_lyr_ECHAM5 <- MEAN_FIELD$PREC -MEAN_FIELD$EVAP
isot_GM_ECHAM5 <- simpleawmean(apply(MEAN_FIELD$PREC - MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 48))
#CESM
load("DATA/SISAL1k_MeanField_CESM.RData")
isot_lyr_CESM <- MEAN_FIELD$PREC - MEAN_FIELD$EVAP[,96:1]
isot_GM_CESM <- simpleawmean(apply(MEAN_FIELD$PREC - MEAN_FIELD$EVAP[,96:1],c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 96))
#GISS
load("DATA/SISAL1k_MeanField_GISS.RData")
isot_lyr_GISS <- MEAN_FIELD$PREC -MEAN_FIELD$EVAP
isot_GM_GISS <- simpleawmean(apply(MEAN_FIELD$PREC - MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 90))
#isoGSM
load("DATA/SISAL1k_MeanField_isoGSM.RData")
isot_lyr_isoGSM <- MEAN_FIELD$PREC -MEAN_FIELD$EVAP
isot_GM_isoGSM <- simpleawmean(apply(MEAN_FIELD$PREC - MEAN_FIELD$EVAP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 94))
rm(MEAN_FIELD)
```
Range Layer:
## Range Layer:
```{r}
library(nest)
library(PaleoSpec)
source("Functions/downsample_field.R")
source("Functions/aw_mean.R")
isot_lyr_HadCM3_ds <- downsample_field(isot_lyr_HadCM3, 96, 48)
isot_lyr_ECHAM5_ds <- downsample_field(isot_lyr_ECHAM5, 96, 48)
isot_lyr_isoGSM_ds   <- downsample_field(isot_lyr_isoGSM,   96, 48)
isot_lyr_GISS_ds   <- downsample_field(isot_lyr_GISS,   96, 48)
isot_lyr_CESM_ds   <- downsample_field(isot_lyr_CESM,   96, 48)

mean_lyr = (isot_lyr_HadCM3_ds + isot_lyr_ECHAM5_ds + isot_lyr_isoGSM_ds + isot_lyr_GISS_ds + isot_lyr_CESM_ds)/5

GM_HadCM3 = simpleawmean(isot_lyr_HadCM3_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_ECHAM5 = simpleawmean(isot_lyr_ECHAM5_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_isoGSM = simpleawmean(isot_lyr_isoGSM_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_GISS = simpleawmean(isot_lyr_GISS_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_CESM = simpleawmean(isot_lyr_CESM_ds, lats = seq(from = -90, to = 90, length.out = 48))

isot_lyr_diff <- array(dim = c(96, 48))
isot_lyr_diff_withoutmean <- array(dim = c(96, 48))
for(ii in 1:96){
  for(jj in 1:48){
    isot_lyr_diff[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj], 
                                        isot_lyr_ECHAM5_ds[ii,jj], 
                                        isot_lyr_isoGSM_ds[ii,jj], 
                                        isot_lyr_GISS_ds[ii,jj], 
                                        isot_lyr_CESM_ds[ii,jj]), na.rm = T), na.rm = T)
    
    isot_lyr_diff_withoutmean[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj]-GM_HadCM3, 
                                                    isot_lyr_ECHAM5_ds[ii,jj]-GM_ECHAM5, 
                                                    isot_lyr_isoGSM_ds[ii,jj]-GM_isoGSM, 
                                                    isot_lyr_GISS_ds[ii,jj]-GM_GISS, 
                                                    isot_lyr_CESM_ds[ii,jj]-GM_CESM), na.rm = T), na.rm = T)
  }
}

rm(ii,jj)
```

```{r pressure, echo=FALSE, warning=FALSE}
source("Functions/STACYmap_PMIL_discrete.R")

plot_HadCM3 <- STACYmap_discrete(rbind((isot_lyr_HadCM3)[49:96,],(isot_lyr_HadCM3)[1:48,]),
                                 legend_name = list(grid = "P-E (mm/year)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 5000, "min" = -5000),
                                 labels_discrete = c(-5000,"",-2500,"",0,"",2500,"",5000), 
                                 discrete_breaks = seq(-5000,5000,by = 1250)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("iHadCM3, GM: ",round(simpleawmean(isot_lyr_HadCM3), digits = 1), "mm/year"))

#plot_HadCM3

plot_ECHAM5 <- STACYmap_discrete(rbind(isot_lyr_ECHAM5[49:96,1:48],isot_lyr_ECHAM5[1:48,1:48]),
                                 legend_name = list(grid = "P-E (mm/year)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 5000, "min" = -5000),
                                 labels_discrete = c(-5000,"",-2500,"",0,"",2500,"",5000), 
                                 discrete_breaks = seq(-5000,5000,by = 1250)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("ECHAM5-wiso, GM: ",round(simpleawmean(isot_lyr_ECHAM5, lats = seq(from = -90,to = 90,length.out = 48)), digits = 1), "mm/year"))

#plot_ECHAM5

plot_isoGSM <- STACYmap_discrete(rbind(isot_lyr_isoGSM[97:192,1:94],isot_lyr_isoGSM[1:96,1:94]),
                                 legend_name = list(grid = "P-E (mm/year)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 5000, "min" = -5000),
                                 labels_discrete = c(-5000,"",-2500,"",0,"",2500,"",5000), 
                                 discrete_breaks = seq(-5000,5000,by = 1250)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("isoGSM, GM: ",round(simpleawmean(isot_lyr_isoGSM, lats = seq(from = -90,to = 90,length.out = 96)), digits = 1), "mm/year"))
  

#plot_CCSM

plot_GISS <- STACYmap_discrete(rbind(isot_lyr_GISS[73:144,1:90],isot_lyr_GISS[1:72,1:90]),
                               legend_name = list(grid = "P-E (mm/year)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 5000, "min" = -5000),
                                 labels_discrete = c(-5000,"",-2500,"",0,"",2500,"",5000), 
                                 discrete_breaks = seq(-5000,5000,by = 1250)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("GISS-E2-R, GM: ",round(simpleawmean(isot_lyr_GISS, lats = seq(from = -90,to = 90,length.out = 90)), digits = 1), "mm/year"))

#plot_GISS

plot_CESM <- STACYmap_discrete(rbind(isot_lyr_CESM[73:144,1:96],isot_lyr_CESM[1:72,1:96]),
                               legend_name = list(grid = "P-E (mm/year)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 5000, "min" = -5000),
                                 labels_discrete = c(-5000,"",-2500,"",0,"",2500,"",5000), 
                                 discrete_breaks = seq(-5000,5000,by = 1250)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("CESM, GM: ",round(simpleawmean(isot_lyr_CESM, lats = seq(from = -90,to = 90,length.out = 94)), digits = 1), "mm/year"))
  


  Plot_lyr = rbind(isot_lyr_diff[49:96,1:48],isot_lyr_diff[1:48,1:48])
  #Plot_lyr[Plot_lyr>25] = NA
  
  plot_diff <- STACYmap_discrete(gridlyr =  Plot_lyr, 
                                 legend_names = list(grid = "P-E range (mm/year)"), graticules = T, 
                                 colorscheme = RColorBrewer::brewer.pal(9, 'Reds'), 
                                 limits_color = list("max" = 4000, "min" = 0),
                                 labels_discrete = c(0,"","", "",2000,"","","",4000), 
                                 discrete_breaks = seq(0,4000,length.out = 9)) +
    theme(panel.border = element_blank(), legend.background = element_blank(), 
          axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
    ggtitle("P-E range (mm/year)")



#plot_diff

library(ggpubr)
plot <- ggarrange(plot_ECHAM5, plot_GISS, plot_CESM, plot_HadCM3, plot_isoGSM, plot_diff,
                  labels = c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)"),
                  ncol = 3, nrow = 2)

#plot
  plot  %>% ggsave(filename = "Plots/RevFig_2_SimOverview_PREC-EVAP.pdf", plot = .,
                 width = 3*12, height = 2*8.3, units = 'cm', dpi = 'print', device = "pdf")
  plot  %>% ggsave(filename = "Plots/RevFig_2_SimOverview_PREC-EVAP.png", plot = ., 
                 width = 36, height = 16, units = 'cm', dpi = 'print', device = "png")

plot
```

#3 Latitudinal Plot over temp, precip, isot, and itif for all models

```{r}

COLZ = c(rgb(112,160,205, max = 255), rgb(0,52,102, max = 255), rgb(178,178,178, max = 255),rgb(0,121,0, max = 255), rgb(196,121,0, max = 255))

pdf(width=7,height=5,file="Plots/RevFig_3_Latitudeplots.pdf")

for(variable in c("TEMP", "PREC", "ISOT", "ITIF", "EVAP")){
  for(Model in c("HadCM3", "ECHAM5", "GISS", "isoGSM", "CESM")){
    load(paste0("DATA/SISAL1k_MeanField_",Model,".RData"))
    assign(paste0("tmp_", Model), apply(MEAN_FIELD[[variable]],2, mean, na.rm = T))
  }
  if(variable == "TEMP"){labeltext = "T in °C"
  title = "Temperature"}
  if(variable == "PREC"){labeltext = "P in mm/year"
  title = "Precipitation"}
  if(variable == "ISOT"){labeltext = TeX("$\\delta^{18}O)$ in permil")
  title = "isotopic composition of precipitation"}
  if(variable == "ITIF"){
    tmp_HadCM3[c(1,73)] = NA
    labeltext = TeX("$\\delta^{18}O_{iw})$ in permil")
    title = "Isotopic composition of precipitation, infiltration weighted"
  }
  if(variable == "EVAP"){
    tmp_CESM = tmp_CESM[96:1]
    labeltext = "E in mm/year"
  title = "Evaporation"}
  
  ylimz = range(c(tmp_ECHAM5, tmp_CESM, tmp_isoGSM, tmp_HadCM3, tmp_GISS), na.rm = T)
  
  par(mar=c(5, 5, 4, 2) + 0.1)
  plot(seq(90,-90,length.out = length(tmp_ECHAM5)),tmp_ECHAM5,  col = COLZ[1], type = "l", xlim = c(-90,90), ylim = ylimz, main = title, xlab = "latitude in °N", ylab = labeltext)
  lines(seq(90,-90,length.out = length(tmp_GISS)), tmp_GISS, col = COLZ[2])
  lines(seq(90,-90,length.out = length(tmp_CESM)), tmp_CESM, col = COLZ[3])
  lines(seq(90,-90,length.out = length(tmp_HadCM3)), tmp_HadCM3, col = COLZ[4])
  lines(seq(90,-90,length.out = length(tmp_isoGSM)), tmp_isoGSM, col = COLZ[5])
  
  legend("bottom", legend = c("ECHAM5", "GISS-E2-R", "iCESM", "iHadCM3", "isoGSM"), text.col = COLZ[1:5])
}
dev.off()
```

# LIA and MCA
LIA goes from 100-400BP (1550-1850)
MCA goes from 700-1000BP (850-1150)

```{r}
source("Functions/aw_mean.R")
No.digits = 2
for(Model in c("HadCM3", "ECHAM5", "GISS", "isoGSM", "CESM")){
  load(paste0("../202009_SISAL1k/Data/Annual_VarFields/Annual_",Model,"_ISOT.RData"))
  GM <- apply(ANNUAL,3, simpleawmean,lats = seq(from = -90, to = 90, length.out = dim(ANNUAL)[2]))
  bstrap = c()
  for(n in 1:1000){
    bstrap = c(bstrap,mean(sample(GM,length(GM),replace=T), na.rm = T))
    }
  print(paste0(Model,"-GMST is ",round(mean(GM, na.rm = T), digits = No.digits)," (",round(quantile(as.numeric(bstrap), probs = 0.05, na.rm = T), digits = No.digits),", ",round(quantile(as.numeric(bstrap), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
  #LIA
  GM <- apply(ANNUAL[,,700:1000],3, simpleawmean,lats = seq(from = -90, to = 90, length.out = dim(ANNUAL)[2]))
  bstrap = c()
  for(n in 1:1000){
    bstrap = c(bstrap,mean(sample(GM,length(GM),replace=T), na.rm = T))
    }
  print(paste0("   LIA: ",Model,"-GMST is ",round(mean(GM, na.rm = T), digits = No.digits)," (",round(quantile(as.numeric(bstrap), probs = 0.05, na.rm = T), digits = No.digits),", ",round(quantile(as.numeric(bstrap), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
  #LIA
  GM <- apply(ANNUAL[,,1:300],3, simpleawmean,lats = seq(from = -90, to = 90, length.out = dim(ANNUAL)[2]))
  bstrap = c()
  for(n in 1:1000){
    bstrap = c(bstrap,mean(sample(GM,length(GM),replace=T), na.rm = T))
    }
  print(paste0("   MCA: ",Model,"-GMST is ",round(mean(GM, na.rm = T), digits = No.digits)," (",round(quantile(as.numeric(bstrap), probs = 0.05, na.rm = T), digits = No.digits),", ",round(quantile(as.numeric(bstrap), probs = 0.95, na.rm = T), digits = No.digits),")"))
  
}

```

