---
title: "SimulationOverview"
author: "Janica Bühler"
date: "4 Juni 2021"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(tidyverse)
source("Functions/aw_mean.R")
```


```{r read in Data}
#HadCM3
load("DATA/SISAL1k_MeanField_HadCM3.RData")
isot_lyr_HadCM3 <- MEAN_FIELD$TEMP
isot_GM_HadCM3 <- simpleawmean(apply(MEAN_FIELD$TEMP,c(1,2),mean,na.rm=TRUE))
#ECHAM5
load("DATA/SISAL1k_MeanField_ECHAM5.RData")
isot_lyr_ECHAM5 <- MEAN_FIELD$TEMP
isot_GM_ECHAM5 <- simpleawmean(apply(MEAN_FIELD$TEMP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 48))
#CESM
load("DATA/SISAL1k_MeanField_CESM.RData")
isot_lyr_CESM <- MEAN_FIELD$TEMP
isot_GM_CESM <- simpleawmean(apply(MEAN_FIELD$TEMP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 96))
#GISS
load("DATA/SISAL1k_MeanField_GISS.RData")
isot_lyr_GISS <- MEAN_FIELD$TEMP
isot_GM_GISS <- simpleawmean(apply(MEAN_FIELD$TEMP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 90))
#isoGSM
load("DATA/SISAL1k_MeanField_isoGSM.RData")
isot_lyr_isoGSM <- MEAN_FIELD$TEMP
isot_GM_isoGSM <- simpleawmean(apply(MEAN_FIELD$TEMP,c(1,2),mean,na.rm=TRUE), lats = seq(from = -90,to = 90,length.out = 94))
rm(MEAN_FIELD)
```

## Range Layer:
```{r}
library(nest)
library(PaleoSpec)
source("Functions/downsample_field.R")
source("Functions/aw_mean.R")
isot_lyr_HadCM3_ds <- downsample_field(isot_lyr_HadCM3, 96, 48)
isot_lyr_ECHAM5_ds <- downsample_field(isot_lyr_ECHAM5, 96, 48)
isot_lyr_isoGSM_ds   <- downsample_field(isot_lyr_isoGSM,   96, 48)
isot_lyr_GISS_ds   <- downsample_field(isot_lyr_GISS,   96, 48)
isot_lyr_CESM_ds   <- downsample_field(isot_lyr_CESM,   96, 48)

mean_lyr = (isot_lyr_HadCM3_ds + isot_lyr_ECHAM5_ds + isot_lyr_isoGSM_ds + isot_lyr_GISS_ds + isot_lyr_CESM_ds)/5

GM_HadCM3 = simpleawmean(isot_lyr_HadCM3_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_ECHAM5 = simpleawmean(isot_lyr_ECHAM5_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_isoGSM = simpleawmean(isot_lyr_isoGSM_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_GISS = simpleawmean(isot_lyr_GISS_ds, lats = seq(from = -90, to = 90, length.out = 48))
GM_CESM = simpleawmean(isot_lyr_CESM_ds, lats = seq(from = -90, to = 90, length.out = 48))

isot_lyr_diff <- array(dim = c(96, 48))
isot_lyr_diff_withoutmean <- array(dim = c(96, 48))
for(ii in 1:96){
  for(jj in 1:48){
    isot_lyr_diff[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj], 
                                        isot_lyr_ECHAM5_ds[ii,jj], 
                                        isot_lyr_isoGSM_ds[ii,jj], 
                                        isot_lyr_GISS_ds[ii,jj], 
                                        isot_lyr_CESM_ds[ii,jj]), na.rm = T), na.rm = T)
    
    isot_lyr_diff_withoutmean[ii,jj] = diff(range(c(isot_lyr_HadCM3_ds[ii,jj]-GM_HadCM3, 
                                                    isot_lyr_ECHAM5_ds[ii,jj]-GM_ECHAM5, 
                                                    isot_lyr_isoGSM_ds[ii,jj]-GM_isoGSM, 
                                                    isot_lyr_GISS_ds[ii,jj]-GM_GISS, 
                                                    isot_lyr_CESM_ds[ii,jj]-GM_CESM), na.rm = T), na.rm = T)
  }
}

rm(ii,jj)
```



## Plot isot

```{r pressure, echo=FALSE, warning=FALSE}
source("Functions/STACYmap_PMIL_discrete.R")

plot_HadCM3 <- STACYmap_discrete(rbind((isot_lyr_HadCM3)[49:96,],(isot_lyr_HadCM3)[1:48,]),
                                 legend_name = list(grid = "T (°C)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 60, "min" = -60),
                                 labels_discrete = c("-60", "", "-40", "", "-20", "", "0", "", "20", "", "40", "", "60"), 
                                 discrete_breaks = seq(-60,60, by = 10)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("iHadCM3, GM: ",round(simpleawmean(isot_lyr_HadCM3), digits = 1), "°C"))

#plot_HadCM3

plot_ECHAM5 <- STACYmap_discrete(rbind(isot_lyr_ECHAM5[49:96,1:48],isot_lyr_ECHAM5[1:48,1:48]),
                                 legend_name = list(grid = "T (°C)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 60, "min" = -60),
                                 labels_discrete = c("-60", "", "-40", "", "-20", "", "0", "", "20", "", "40", "", "60"), 
                                 discrete_breaks = seq(-60,60, by = 10)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("ECHAM5-wiso, GM: ",round(simpleawmean(isot_lyr_ECHAM5, lats = seq(from = -90,to = 90,length.out = 48)), digits = 1), "°C"))

#plot_ECHAM5

plot_isoGSM <- STACYmap_discrete(rbind(isot_lyr_isoGSM[97:192,1:94],isot_lyr_isoGSM[1:96,1:94]),
                                 legend_name = list(grid = "T (°C)"), graticules = T, colorscheme = "temp", 
                                 limits_color = list("max" = 60, "min" = -60),
                                 labels_discrete = c("-60", "", "-40", "", "-20", "", "0", "", "20", "", "40", "", "60"), 
                                 discrete_breaks = seq(-60,60, by = 10)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("isoGSM, GM: ",round(simpleawmean(isot_lyr_isoGSM, lats = seq(from = -90,to = 90,length.out = 94)), digits = 1), "°C"))

#plot_CCSM

plot_GISS <- STACYmap_discrete(rbind(isot_lyr_GISS[73:144,1:90],isot_lyr_GISS[1:72,1:90]),
                               legend_name = list(grid = "T (°C)"), graticules = T, colorscheme = "temp", 
                               limits_color = list("max" = 60, "min" = -60),
                               labels_discrete = c("-60", "", "-40", "", "-20", "", "0", "", "20", "", "40", "", "60"), 
                               discrete_breaks = seq(-60,60, by = 10)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("GISS-E2-R, GM: ",round(simpleawmean(isot_lyr_GISS, lats = seq(from = -90,to = 90,length.out = 90)), digits = 1), "°C"))

#plot_GISS

plot_CESM <- STACYmap_discrete(rbind(isot_lyr_CESM[73:144,1:96],isot_lyr_CESM[1:72,1:96]),
                               legend_name = list(grid = "T (°C)"), graticules = T, colorscheme = "temp", 
                               limits_color = list("max" = 60, "min" = -60),
                               labels_discrete = c("-60", "", "-40", "", "-20", "", "0", "", "20", "", "40", "", "60"), 
                               discrete_breaks = seq(-60,60, by = 10)) +
  theme(panel.border = element_blank(), legend.background = element_blank(), axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
  ggtitle(paste0("iCESM, GM: ",round(simpleawmean(isot_lyr_CESM, lats = seq(from = -90,to = 90,length.out = 96)), digits = 1), "°C"))


  Plot_lyr = rbind(isot_lyr_diff[49:96,1:48],isot_lyr_diff[1:48,1:48])
  Plot_lyr[Plot_lyr>25] = NA
  
  plot_diff <- STACYmap_discrete(gridlyr =  Plot_lyr, 
                                 legend_names = list(grid = "T range (°C)"), graticules = T, 
                                 colorscheme = RColorBrewer::brewer.pal(9, 'Reds'), 
                                 limits_color = list("max" = 25, "min" = 0),
                                 labels_discrete = c(0,"",5,"",10,"",15,"",20,"",25), 
                                 discrete_breaks = c(0,2.5,5,7.5, 10,12.5,15,17.5,20,22.5,25)) +
    theme(panel.border = element_blank(), legend.background = element_blank(), 
          axis.text = element_blank(), legend.text = element_text(size = 10),plot.title = element_text(hjust = 0.5)) +
    ggtitle("T range (°C)")



#plot_diff

library(ggpubr)
plot <- ggarrange(plot_ECHAM5, plot_GISS, plot_CESM, plot_HadCM3, plot_isoGSM, plot_diff,
                  labels = c("(a)", "(b)", "(c)", "(d)", "(e)", "(f)"),
                  ncol = 3, nrow = 2)

#plot
  plot  %>% ggsave(filename = "Plots/Supplement/SFig_3_SimOverview_TEMP.pdf", plot = .,
                 width = 3*12, height = 2*8.3, units = 'cm', dpi = 'print', device = "pdf")
  plot  %>% ggsave(filename = "Plots/Supplement/SFig_3_SimOverview_TEMP.png", plot = ., 
                 width = 36, height = 16, units = 'cm', dpi = 'print', device = "png")

plot
```