---
title: "Correlation comparison"
author: "Janica Bühler"
date: "18 März 2021"
output: html_document
---

```{r message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(tidyverse)
library(latex2exp)
library(zoo)
library(nest)
library(PaleoSpec)
source("Functions/projection_ptlyr.R")
source("Functions/STACYmap_PMIL.R")
source("Functions/STACYmap_PMIL_NAgrid_discrete.R")
```


We compare the correlation between simulated d18O and temperature/precipitation also to the speleothems:

Hier follows the pointwise correlation for the cave locations:
```{r message=FALSE, warning=FALSE}
CORR_CAVE = list()
ENTITY_INFO <- read.csv("DATA/SISAL1k_entity_info.csv")

for(Model in c("HadCM3", "ECHAM5", "GISS", "isoGSM", "CESM")){
  name = Model
  
  DATA <- read.csv(paste0("DATA/SISAL1k_ds_",name,".csv"))
  
  CORR_CAVE[[Model]] <- list(entity_id = numeric(length(ENTITY_INFO$entity_id)),
                  lon = numeric(length(ENTITY_INFO$entity_id)),
                  lat = numeric(length(ENTITY_INFO$entity_id)))

  for(var in c("TEMP", "PREC")){
    CORR_CAVE[[Model]][[paste0("CORR_",var)]] <- numeric(length(ENTITY_INFO$entity_id))
    CORR_CAVE[[Model]][[paste0("p_", var)]] <- numeric(length(ENTITY_INFO$entity_id))
    for(ii in 1:length(ENTITY_INFO$entity_id)){
      entity = ENTITY_INFO$entity_id[ii]
      CORR_CAVE[[Model]]$entity_id[ii] = entity
      CORR_CAVE[[Model]]$lon[ii] = ENTITY_INFO$longitude[ii]
      CORR_CAVE[[Model]]$lat[ii] = ENTITY_INFO$latitude[ii]
      data_rec = DATA %>% filter(entity_id == entity)
      # zoo cannot handle objects where order.by has two elements which is why they are sorted out here (no better option found)
      double_time <- data_rec %>% group_by(year_BP) %>% count() %>% filter(n>1)
      data_rec <- data_rec %>% filter(!year_BP %in% double_time$year_BP)
      if(length(data_rec$year_BP)>4){
        record = zoo(x = data_rec$d18O_measurement, order.by = data_rec$year_BP)
        sim = zoo(x = na.omit(data_rec[[paste0(var)]]), order.by = data_rec$year_BP[!is.na(data_rec[[paste0(var)]])])
        COR <- nexcf_ci(record, sim)
        
        CORR_CAVE[[Model]][[paste0("CORR_",var)]][ii] = COR$rxy
        CORR_CAVE[[Model]][[paste0("p_",var)]][ii] = COR$pval
        CORR_CAVE[[Model]][[paste0("neff_",var)]][ii] = COR$neff
        CORR_CAVE[[Model]][[paste0("neff_ratio",var)]][ii] = COR$neff/length(data_rec$d18O_measurement)
      }else{
        CORR_CAVE[[Model]][[paste0("CORR_",var)]][ii] = NA
        CORR_CAVE[[Model]][[paste0("p_",var)]][ii] = NA
        CORR_CAVE[[Model]][[paste0("neff_",var)]][ii] = NA
        CORR_CAVE[[Model]][[paste0("neff_ratio",var)]][ii] = NA
      }
    }
  }
}
```

get an agreement plot:

```{r}
#First all plots need to be of the same resolution. For this, there is already a function:
source("Functions/downsample_field.R")
CORR_FIELDS <- list()
load("DATA/SISAL1k_CorrField_HadCM3.RData")
CORR_FIELDS$HadCM3$TEMP <- downsample_field(CORR_FIELD$TEMP, 96, 48)
CORR_FIELDS$HadCM3$TEMP_P <- downsample_field(CORR_FIELD$TEMP_P, 96, 48)
CORR_FIELDS$HadCM3$PREC <- downsample_field(CORR_FIELD$PREC, 96, 48)
CORR_FIELDS$HadCM3$PREC_P <- downsample_field(CORR_FIELD$PREC_P, 96, 48)
load("DATA/SISAL1k_CorrField_ECHAM5.RData")
CORR_FIELDS$ECHAM5$TEMP <- downsample_field(CORR_FIELD$TEMP, 96, 48)
CORR_FIELDS$ECHAM5$TEMP_P <- downsample_field(CORR_FIELD$TEMP_P, 96, 48)
CORR_FIELDS$ECHAM5$PREC <- downsample_field(CORR_FIELD$PREC, 96, 48)
CORR_FIELDS$ECHAM5$PREC_P <- downsample_field(CORR_FIELD$PREC_P, 96, 48)
load("DATA/SISAL1k_CorrField_isoGSM.RData")
CORR_FIELDS$isoGSM$TEMP <- downsample_field(CORR_FIELD$TEMP, 96, 48)
CORR_FIELDS$isoGSM$TEMP_P <- downsample_field(CORR_FIELD$TEMP_P, 96, 48)
CORR_FIELDS$isoGSM$PREC <- downsample_field(CORR_FIELD$PREC, 96, 48)
CORR_FIELDS$isoGSM$PREC_P <- downsample_field(CORR_FIELD$PREC_P, 96, 48)
load("DATA/SISAL1k_CorrField_CESM.RData")
CORR_FIELDS$CESM$TEMP <- downsample_field(CORR_FIELD$TEMP, 96, 48)
CORR_FIELDS$CESM$TEMP_P <- downsample_field(CORR_FIELD$TEMP_P, 96, 48)
CORR_FIELDS$CESM$PREC <- downsample_field(CORR_FIELD$PREC, 96, 48)
CORR_FIELDS$CESM$PREC_P <- downsample_field(CORR_FIELD$PREC_P, 96, 48)
load("DATA/SISAL1k_CorrField_GISS.RData")
CORR_FIELDS$GISS$TEMP <- downsample_field(CORR_FIELD$TEMP, 96, 48)
CORR_FIELDS$GISS$TEMP_P <- downsample_field(CORR_FIELD$TEMP_P, 96, 48)
CORR_FIELDS$GISS$PREC <- downsample_field(CORR_FIELD$PREC, 96, 48)
CORR_FIELDS$GISS$PREC_P <- downsample_field(CORR_FIELD$PREC_P, 96, 48)


Model_list = c("HadCM3", "ECHAM5", "GISS", "isoGSM", "CESM")

MEAN_FIELD = list(TEMP = array(dim = c(96,48)), PREC = array(dim = c(96,48)))
AGREE = list(TEMP = array(dim = c(96,48), data = 0), PREC = array(dim = c(96,48), data = 0))
MEAN_Points = list(TEMP = numeric(length(ENTITY_INFO$entity_id)),
                    PREC = numeric(length(ENTITY_INFO$entity_id)))
AGREE_Points = list(TEMP = numeric(length(ENTITY_INFO$entity_id)),
                    PREC = numeric(length(ENTITY_INFO$entity_id)))

for(lon in 1:96){
  for(lat in 1:48){
    for(VAR in c("TEMP", "PREC")){
      tmp_list = c(CORR_FIELDS$HadCM3[[VAR]][lon,lat],
                 CORR_FIELDS$ECHAM5[[VAR]][lon,lat],
                 CORR_FIELDS$isoGSM[[VAR]][lon,lat],
                 CORR_FIELDS$CESM[[VAR]][lon,lat],
                 CORR_FIELDS$GISS[[VAR]][lon,lat])
      p_list = c(CORR_FIELDS$HadCM3[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$ECHAM5[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$isoGSM[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$CESM[[paste0(VAR,"_P")]][lon,lat],
                 CORR_FIELDS$GISS[[paste0(VAR,"_P")]][lon,lat])
    tmp_list[p_list>0.1] = NA
    MEAN_FIELD[[VAR]][lon,lat] = mean(tmp_list, na.rm = T)
    if(sum(is.na(tmp_list))>3){MEAN_FIELD[[VAR]][lon,lat] = NA}
    }
  }
}

for(ii in 1:length(ENTITY_INFO$entity_id)){
  for(VAR in c("TEMP","PREC")){
    tmp = c(CORR_CAVE$HadCM3[[paste0("CORR_",VAR)]][ii], 
            CORR_CAVE$ECHAM5[[paste0("CORR_",VAR)]][ii], 
            CORR_CAVE$GISS[[paste0("CORR_",VAR)]][ii], 
            CORR_CAVE$isoGSM[[paste0("CORR_",VAR)]][ii], 
            CORR_CAVE$CESM[[paste0("CORR_",VAR)]][ii])
    tmp_p = c(CORR_CAVE$HadCM3[[paste0("p_",VAR)]][ii], 
            CORR_CAVE$ECHAM5[[paste0("p_",VAR)]][ii], 
            CORR_CAVE$GISS[[paste0("p_",VAR)]][ii], 
            CORR_CAVE$isoGSM[[paste0("p_",VAR)]][ii], 
            CORR_CAVE$CESM[[paste0("p_",VAR)]][ii])
    tmp[tmp_p>0.1] = NA
    MEAN_Points[[VAR]][ii] = mean(tmp, na.rm = T)
    if(all(is.na(tmp))){MEAN_Points[[VAR]][ii] = NA}
  }
}

for(Model in Model_list){
  for(lon in 1:96){
    for(lat in 1:48){
      if(!is.na(MEAN_FIELD$TEMP[lon,lat]) & !is.na(CORR_FIELDS[[Model]]$TEMP[lon,lat])){
        if(sign(MEAN_FIELD$TEMP[lon,lat]) == sign(CORR_FIELDS[[Model]]$TEMP[lon,lat])){AGREE$TEMP[lon,lat] = AGREE$TEMP[lon,lat]+1}
      }
      if(!is.na(MEAN_FIELD$PREC[lon,lat]) & !is.na(CORR_FIELDS[[Model]]$PREC[lon,lat])){
       if(sign(MEAN_FIELD$PREC[lon,lat]) == sign(CORR_FIELDS[[Model]]$PREC[lon,lat])){AGREE$PREC[lon,lat] = AGREE$PREC[lon,lat]+1} 
      }
    }
  }
  
  
  for(entity in 1:length(ENTITY_INFO$entity_id)){
    if(!is.na(CORR_CAVE[[Model]]$p_TEMP[entity])& !is.na(MEAN_Points$TEMP[entity]) & !is.na(CORR_CAVE[[Model]]$CORR_TEMP[entity])){
      if(CORR_CAVE[[Model]]$p_TEMP[entity]<0.1 & sign(CORR_CAVE[[Model]]$CORR_TEMP[entity]) == sign(MEAN_Points$TEMP[entity])){AGREE_Points$TEMP[entity] = AGREE_Points$TEMP[entity]+1}
    }
    if(!is.na(CORR_CAVE[[Model]]$p_PREC[entity]) & !is.na(MEAN_Points$PREC[entity]) & !is.na(CORR_CAVE[[Model]]$CORR_PREC[entity])){
      if(CORR_CAVE[[Model]]$p_PREC[entity]<0.1 & sign(CORR_CAVE[[Model]]$CORR_PREC[entity]) == sign(MEAN_Points$PREC[entity])){AGREE_Points$PREC[entity] = AGREE_Points$PREC[entity]+1}
    }
  }
}


```

Here comes the actual plot:
```{r}
plots <- list()
for(var in c("TEMP", "PREC")){
  for(Model in c("HadCM3", "ECHAM5", "isoGSM", "CESM", "GISS")){
    name = Model
    
    Plot_lyr = CORR_FIELDS[[Model]][[var]]
    Plot_lyr_p = CORR_FIELDS[[Model]][[paste0(var, "_P")]]
    Plot_lyr[Plot_lyr_p > 0.1] = NA
    Plot_lyr[1,1] = 1
    Plot_lyr[1,2] = -1

    ##### Point Layer
    Point_Lyr <- as.tibble(CORR_CAVE[[Model]]) %>% filter(!is.na(p_TEMP)) %>% filter(p_TEMP<0.1) %>% select(entity_id, lon,lat,CORR_TEMP) %>% rename(value = CORR_TEMP)
    Point_Lyr_not <- as.tibble(CORR_CAVE[[Model]]) %>% filter(!entity_id %in% Point_Lyr$entity_id) %>% select(entity_id, lon,lat,CORR_TEMP) %>% rename(value = CORR_TEMP)
    Point_Lyr_not_p <- projection_ptlyr(as.data.frame(Point_Lyr_not %>% select(lon,lat,value)), projection = as.character('+proj=robin +datum=WGS84'))
    Point_Lyr_p <- projection_ptlyr(as.data.frame(Point_Lyr %>% select(lon,lat,value)), projection = as.character('+proj=robin +datum=WGS84'))

    #Plot
    GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE <- 4
    NA_plot_lyr = Plot_lyr
    NA_plot_lyr[!is.na(NA_plot_lyr)] = 0
    NA_plot_lyr[is.na(NA_plot_lyr)] = 1
    
    leg_name = TeX("$\\rho (T, \\delta^{18}O)$")
    if(var == "PREC"){leg_name = TeX("$\\rho (P, \\delta^{18}O)$")}

    plots[[paste0(var,"_",Model)]] <-  STACYmap_NA(gridlyr = rbind(Plot_lyr[49:96,],Plot_lyr[1:48,]), graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = rbind(NA_plot_lyr[49:96],NA_plot_lyr[1:48,]), NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-1", "", "", "-0.5", "", "", "0", "", "", "0.5", "", "", "1"), 
                                                discrete_breaks = seq(-1,1,length.out = 13)) +
      geom_point(data = as.data.frame(Point_Lyr_not_p), aes(x = long, y = lat), shape = 20, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE-1.5) +
      geom_point(data = as.data.frame(Point_Lyr_p), aes(x = long, y = lat, fill = layer), shape = 21, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE) +
      theme(panel.border = element_blank(),
            legend.background = element_blank(),
            axis.text = element_blank(),
            text = element_text(size = 12),
            legend.title = element_text(size = 12))
    
    if(var == "TEMP"){
      plots[[paste0(var,"_",Model)]] = plots[[paste0(var,"_",Model)]]#+ggtitle(name)
    }else{
      plots[[paste0(var,"_",Model)]] = plots[[paste0(var,"_",Model)]]#+ggtitle(" ")
    }
    
    #which is higher plot:
    if(var == "TEMP"){
      Plot_lyr_T = CORR_FIELDS[[Model]]$TEMP
      Plot_lyr_T[CORR_FIELDS[[Model]]$TEMP_P > 0.1] = NA
      Plot_lyr_P = CORR_FIELDS[[Model]]$PREC
      Plot_lyr_P[CORR_FIELDS[[Model]]$PREC_P > 0.1] = NA
      
      Plot_lyr = abs(Plot_lyr_T)
      Plot_lyr[Plot_lyr<=abs(Plot_lyr_P)&!is.na(Plot_lyr)&!is.na(Plot_lyr_P)] = -abs(Plot_lyr_P[Plot_lyr<=abs(Plot_lyr_P)&!is.na(Plot_lyr)&!is.na(Plot_lyr_P)])
      Plot_lyr[is.na(Plot_lyr_P)] = NA
      Plot_lyr[1,1] = 1
      Plot_lyr[1,2] = -1
      NA_plot_lyr = Plot_lyr
      NA_plot_lyr[!is.na(NA_plot_lyr)] = 0
      NA_plot_lyr[is.na(NA_plot_lyr)] = 1
      
      leg_name = TeX("max($\\rho (T,P))$")
      
      plots[[paste0("Stronger_",Model)]] <-  STACYmap_NA(gridlyr = rbind(Plot_lyr[49:96,],Plot_lyr[1:48,]), graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = rbind(NA_plot_lyr[49:96],NA_plot_lyr[1:48,]), NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-1", "", "", "-0.5", "", "", "0", "", "", "0.5", "", "", "1"), 
                                                discrete_breaks = seq(-1,1,length.out = 13)) +
        theme(panel.border = element_blank(),
              legend.background = element_blank(),
              axis.text = element_blank(),
              text = element_text(size = 12),
              legend.title = element_text(size = 12))+
        ggtitle(" ")
      
      
    }
  }
}

```

```{r}
for(var in c("TEMP", "PREC")){
  Plot_lyr = MEAN_FIELD[[var]]

  ##### Point Layer
  Point_Lyr <- as.tibble(data.frame(lon = ENTITY_INFO$longitude, lat = ENTITY_INFO$latitude, value = MEAN_Points[[var]])) 
  Point_Lyr_not <- Point_Lyr %>% filter(abs(value) < 0.05)
  Point_Lyr <- Point_Lyr %>% filter(abs(value)>0.05)
  Point_Lyr_p <- projection_ptlyr(as.data.frame(Point_Lyr %>% select(lon,lat,value)), projection = as.character('+proj=robin +datum=WGS84'))
  Point_Lyr_not_p <- projection_ptlyr(as.data.frame(Point_Lyr_not %>% select(lon,lat,value)), projection = as.character('+proj=robin +datum=WGS84'))
  
  Point_Lyr_agree <- as.tibble(data.frame(lon = ENTITY_INFO$longitude, lat = ENTITY_INFO$latitude, value = AGREE_Points[[var]])) 
  Point_Lyr_agree <- Point_Lyr_agree %>% filter(value>4) %>% filter(lat %in% Point_Lyr$lat)
  if(length(Point_Lyr_agree$lon)!=0){
    Point_Lyr_agree_p <- projection_ptlyr(as.data.frame(Point_Lyr_agree %>% select(lon,lat,value)), projection = as.character('+proj=robin +datum=WGS84'))
  }
  
  Point_sig <- as.tibble(data.frame(lon = rep(seq(-180+1.875,180-1.875,3.75),48), 
                                    lat = rep(seq(90-1.875,-90+1.875,-3.75),each = 96), 
                                    value = as.numeric(rbind(AGREE[[var]][49:96,],AGREE[[var]][1:48,]))))
  Point_sig$value[Point_sig$value < 5] = NA
  Point_sig_2 <- as_tibble(data.frame(lon = Point_sig$lon[!is.na(Point_sig$value)], 
                                      lat = Point_sig$lat[!is.na(Point_sig$value)], 
                                      value =  Point_sig$value[!is.na(Point_sig$value)]))
  Point_sig_2_p = projection_ptlyr(as.data.frame(Point_sig_2, projection = as.character('+proj=robin +datum=WGS84')))


  #Plot
  GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE <- 3
  NA_plot_lyr = Plot_lyr
  NA_plot_lyr[!is.na(NA_plot_lyr)] = 0
  NA_plot_lyr[is.na(NA_plot_lyr)] = 1
  Plot_lyr[1,1] = 1
  Plot_lyr[1,2] = -1
  
  leg_name = TeX("$\\rho (T, \\delta^{18}O)$")
  if(var == "PREC"){leg_name = TeX("$\\rho (P, \\delta^{18}O)$")}

  if(length(Point_Lyr_agree$lon)!=0){
    
    plots[[paste0(var,"_agree")]] <-  STACYmap_NA(gridlyr = rbind(Plot_lyr[49:96,],Plot_lyr[1:48,]), graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = rbind(NA_plot_lyr[49:96],NA_plot_lyr[1:48,]), NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-1", "", "", "-0.5", "", "", "0", "", "", "0.5", "", "", "1"), 
                                                discrete_breaks = seq(-1,1,length.out = 13)) +
    geom_point(data = as.data.frame(Point_sig_2_p), aes(x = long, y = lat), shape = 3, color = adjustcolor("black", alpha.f = 0.5), size = 0.1) + 
    geom_point(data = as.data.frame(Point_Lyr_not_p), aes(x = long, y = lat), shape = 20, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE-1.5) +
    geom_point(data = as.data.frame(Point_Lyr_p), aes(x = long, y = lat, fill = layer), shape = 21, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE) +
    geom_point(data = as.data.frame(Point_Lyr_agree_p), aes(x = long, y = lat), shape = 3, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE) +
    theme(panel.border = element_blank(),
          legend.background = element_blank(),
          axis.text = element_blank(),
          text = element_text(size = 12),
          legend.title = element_text(size = 12))
  
  }else{
    plots[[paste0(var,"_agree")]] <-  STACYmap_NA(gridlyr = Plot_lyr, graticules = T, colorscheme = rev(RColorBrewer::brewer.pal(9, 'RdBu')[1:8]),
                                                NA_gridlyr = NA_plot_lyr, NA_color = "grey", legend_names = list(grid = leg_name),
                                                labels_discrete = c("-1", "", "", "-0.5", "", "", "0", "", "", "0.5", "", "", "1"), 
                                                discrete_breaks = seq(-1,1,length.out = 13)) +
    geom_point(data = as.data.frame(Point_sig_2_p), aes(x = long, y = lat), shape = 3, color = adjustcolor("black", alpha.f = 0.5), size = 0.1) + 
    geom_point(data = as.data.frame(Point_Lyr_not_p), aes(x = long, y = lat), shape = 20, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE-1.5) +
    geom_point(data = as.data.frame(Point_Lyr_p), aes(x = long, y = lat, fill = layer), shape = 21, color = "black", size = GLOBAL_STACY_OPTIONS$GLOBAL_POINT_SIZE) +
    theme(panel.border = element_blank(),
          legend.background = element_blank(),
          axis.text = element_blank(),
          text = element_text(size = 12),
          legend.title = element_text(size = 12))
  
  }
}
```


Fitting it all together and also the Agreement

```{r}
library(ggplot2)
library(patchwork)
txtsize = 6

row1 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="ECHAM5-wiso", angle = 90) + theme_void() 
row2 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="GISS-E2-R", angle = 90) + theme_void() 
row3 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="iCESM", angle = 90) + theme_void() 
row4 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="iHadCM3", angle = 90) + theme_void() 
row5 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="isoGSM", angle = 90) + theme_void() 
row6 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label="Agreement", angle = 90) + theme_void() 

col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label=TeX("$\\rho (T, \\delta^{18}O)$")) + theme_void() 
col2 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label=TeX("$\\rho (P, \\delta^{18}O)$")) + theme_void() 
col3 <- ggplot() + annotate(geom = 'text', x=1, y=1, size = txtsize, label=TeX("max($\\rho(T,P))$")) + theme_void() 


layoutplot <- "
#aaaaabbbbbccccc
deeeeefffffggggg
deeeeefffffggggg
deeeeefffffggggg
deeeeefffffggggg
deeeeefffffggggg
deeeeefffffggggg
hiiiiijjjjjkkkkk
hiiiiijjjjjkkkkk
hiiiiijjjjjkkkkk
hiiiiijjjjjkkkkk
hiiiiijjjjjkkkkk
hiiiiijjjjjkkkkk
lmmmmmnnnnnooooo
lmmmmmnnnnnooooo
lmmmmmnnnnnooooo
lmmmmmnnnnnooooo
lmmmmmnnnnnooooo
lmmmmmnnnnnooooo
pqqqqqrrrrrsssss
pqqqqqrrrrrsssss
pqqqqqrrrrrsssss
pqqqqqrrrrrsssss
pqqqqqrrrrrsssss
pqqqqqrrrrrsssss
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
tuuuuuvvvvvwwwww
xyyyyyzzzzz#####
xyyyyyzzzzz#####
xyyyyyzzzzz#####
xyyyyyzzzzz#####
xyyyyyzzzzz#####
xyyyyyzzzzz#####
xyyyyyzzzzz#####
"

plotlist <- list(a = col1, b = col2, c = col3, 
                 d = row1, 
                 e= plots$TEMP_ECHAM5+theme(legend.position="none")+ggtitle("a)"),
                 f = plots$PREC_ECHAM5+theme(legend.position="none")+ggtitle("b)"),
                 g = plots$Stronger_ECHAM5+theme(legend.position="none")+ggtitle("c)"),
                 h = row2,
                 i = plots$TEMP_GISS+theme(legend.position="none")+ggtitle("d)"),
                 j = plots$PREC_GISS+theme(legend.position="none")+ggtitle("e)"),
                 k = plots$Stronger_GISS+theme(legend.position="none")+ggtitle("f)"),
                 l = row3,
                 m = plots$TEMP_CESM+theme(legend.position="none")+ggtitle("g)"),
                 n = plots$PREC_CESM+theme(legend.position="none")+ggtitle("h)"),
                 o = plots$Stronger_CESM+theme(legend.position="none")+ggtitle("i)"),
                 p = row4,
                 q = plots$TEMP_HadCM3+theme(legend.position="none")+ggtitle("j)"),
                 r = plots$PREC_HadCM3+theme(legend.position="none")+ggtitle("k)"),
                 s = plots$Stronger_HadCM3+theme(legend.position="none")+ggtitle("l)"),
                 t = row5,
                 u = plots$TEMP_isoGSM+ggtitle("m)"), 
                 v = plots$PREC_isoGSM+ggtitle("n)"),
                 w = plots$Stronger_isoGSM+ggtitle("o)"),
                 x = row6,
                 y = plots$TEMP_agree+ggtitle("p)"), 
                 z = plots$PREC_agree+ggtitle("q)"))

final_plot <- wrap_plots(plotlist, design = layoutplot)

final_plot  %>% ggsave(filename = paste0('SFig_5_Correlation_all.pdf'), plot = ., path = 'Plots/Supplement', 
                 width = 3*10, height = 5*8, units = 'cm', dpi = 'print', device = "pdf")
final_plot  %>% ggsave(filename = paste0('SFig_5_Correlation_all.png'), plot = ., path = 'Plots/Supplement', 
                 width = 3*10, height = 5*8, units = 'cm', dpi = 'print', device = "png")

```

